name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Use your custom PAT instead of the default GITHUB_TOKEN
        token: ${{ secrets.MY_WORKFLOW_PTD }}

    - name: Use PAT in a custom script
      env:
        # Injects the secret as an environment variable
        GH_TOKEN: ${{ secrets.MY_WORKFLOW_PTD }}
      run: |
        curl -H "Authorization: Bearer $GH_TOKEN" https://github.com
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
